import Head from "next/head";
import HeaderPage from './utils/header'
const Andre = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderPage/>
            <div>
                <div>

                    
                </div>
                <div>
                <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
  <path fill="#FF0066" d="M47.1,-44.7C62.8,-31.4,78.5,-15.7,77,-1.4C75.6,12.8,57.1,25.7,41.4,40.1C25.7,54.6,12.8,70.6,-2.4,73C-17.6,75.4,-35.2,64.1,-51.5,49.6C-67.8,35.2,-82.9,17.6,-82.9,0C-82.8,-17.6,-67.8,-35.1,-51.5,-48.4C-35.1,-61.7,-17.6,-70.7,-0.9,-69.8C15.7,-68.9,31.4,-58,47.1,-44.7Z" transform="translate(100 100)" />
</svg>
                </div>
            </div>
        </>
    )
}
export default Andre;
